Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Sunshine - Delacruz");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("Uh, uh, uh, uh");
Console.WriteLine("Uh, uh, tchurururu");
Console.WriteLine("Uh, uh, uh, uh");
Console.WriteLine("Uh, uh, tchurururu");
Console.WriteLine("");
Console.WriteLine("Ali me ganhou");
Console.WriteLine("Depois que você chegou no meu mundo");
Console.WriteLine("Quase tudo mudou");
Console.WriteLine("Parece até miragem");
Console.WriteLine("Nós dois numa paisagem a sós");
Console.WriteLine("Dois sóis");
Console.WriteLine("");
Console.WriteLine("Sorrindo e dançando");
Console.WriteLine("Atrasando o amanhã");
Console.WriteLine("Transando até de manhã");
Console.WriteLine("Como se não existisse");
Console.WriteLine("Como se nunca viesse o após");
Console.WriteLine("Ô, sunshine");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Veja o homem que sou");
Console.WriteLine("Alguém me abençoou");
Console.WriteLine("Quando você me encontrou");
Console.WriteLine("Tudo clareou");
Console.WriteLine("");
Console.WriteLine("Veja o homem que sou");
Console.WriteLine("Alguém me abençoou");
Console.WriteLine("Quando você me encontrou");
Console.WriteLine("Tudo clareou");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("Uh, uh, uh, uh");
Console.WriteLine("Uh, uh, tchurururu");
Console.WriteLine("Uh, uh, uh, uh");
Console.WriteLine("Uh, uh, tchurururu");
Console.WriteLine("");
Console.WriteLine("É tão real, todos podem ver");
Console.WriteLine("Nem é natal, nunca pensei");
Console.WriteLine("Não é normal, muitos querem ter");
Console.WriteLine("E olha que nem é natal");
Console.WriteLine("");
Console.WriteLine("Meu presente");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Veja o homem que sou");
Console.WriteLine("Alguém me abençoou");
Console.WriteLine("Quando você me encontrou");
Console.WriteLine("Tudo clareou");
Console.WriteLine("");
Console.WriteLine("Veja o homem que sou");
Console.WriteLine("Alguém me abençoou");
Console.WriteLine("Quando você me encontrou");
Console.WriteLine("Tudo clareou");
Console.WriteLine("");
Console.WriteLine("Veja o homem que sou");
Console.WriteLine("Alguém me abençoou");
Console.WriteLine("Quando você me encontrou");
Console.WriteLine("Tudo clareou");
Console.WriteLine("");
Console.WriteLine("Veja o homem que sou");
Console.WriteLine("Alguém me abençoou");
Console.WriteLine("Quando você me encontrou");
Console.WriteLine("Tudo clareou");
Console.ResetColor();
